name: mychef
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  direct_select: "^1.0.3"
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter